### ISSUE TITLE
Pipeline 3.4.0.455 not processing wav or mp3 file (MacOSX)

### ISSUE THREAD

**Issue by ambs** [mono/MonoGame#4574]
I tried the GUI and it complain with:

````
Build failed:  ApplicationName='mono', CommandLine='"/Volumes/HDD/Applications/Pipeline.app/Contents/MonoBundle/MGCB.exe" /@:"/Users/ambs/Desktop/TESTE.mgcb" ', CurrentDirectory='/Users/ambs/Desktop', Native error= Cannot find the specified file
````

When running manually (not sure if options are completely correct) I got:

````
mono /Volumes/HDD/Applications/Pipeline.app/Contents/MonoBundle/MGCB.exe /platform:macosx /build:POL-macaron-island-short.wav
-----
chmod: Unable to change file mode on /Volumes/HDD/Applications/Pipeline.app/Contents/MonoBundle/ffmpeg: Operation not permitted
`````

after fixing, it complained yet again

``````
chmod: Unable to change file mode on /Volumes/HDD/Applications/Pipeline.app/Contents/MonoBundle/ffprobe: Operation not permitted
`````
Fixed it again, and the command line succeeded, creating a .xnb file (didn't test it yet, though).

In any case, the GUI continues failing.

Hints?

(those permissions should be fixed during instalation, though).

Happy to give further details if needed.

**Comment by ambs** [comment]
(ok, the command line generated file is not a song, still trying to see how to do that).

**Comment by ambs** [comment]
I think I got the command line working:
```
mono /Volumes/HDD/Applications/Pipeline.app/Contents/MonoBundle/MGCB.exe /processor:SongProcessor /build:POL-macaron-island-short.mp3  /platform:MacOSX
````
but still not hearing a thing, so, probably still wrong.

**Comment by ambs** [comment]
now a different problem, probably. My app running on Mac says: Failed to get buffer bits: Invalid Value, format=Stereo16, size=0, sampleRate=22050

**Comment by cra0zy** [comment]
There was a problem with installer not setting executable permissions on ffmpeg and ffprobe, this has since been fixed in develop branch.

Use: http://teamcity.monogame.net/repository/download/MonoGame_PackageMacAndLinux/latest.lastSuccessful/MonoGame.pkg?guest=1

**Comment by ambs** [comment]
great. But it seems it is not the only problem. Or I am doing things in the bad way :-)

**Comment by ambs** [comment]
(a sound effect created by command line is working perfectly, though)

**Comment by ambs** [comment]
Looking to the pipeline tool code, everything should work. Using in the command line the exact parameters as the GUI shows, it works. Well... adding 'mono' before it.

So, my main question is if 
````
                _buildProcess = View.CreateProcess(FindMGCB(), commands);
````
implicitly calls mono by itself?

**Comment by ambs** [comment]
looking to stackoverflow, it seems it doesn't (?). But it seems strange nobody else complain on this.

**Comment by ambs** [comment]
would love to test a pipeline build to macosx with PipelineController.cs file changed in line 437 to call "mono" first:

`````
                _buildProcess = View.CreateProcess("mono", FindMGCB(), commands);
`````
but can't build it, as my Xamarin edition is the starters' one, and no funds atm to buy it.

**Comment by tomspilman** [comment]
> would love to test a pipeline build to macosx with PipelineController.cs file changed in line 437 to call "mono" first:

@dellis1972 - Is that required or even just safer?

**Comment by ambs** [comment]
I think it is required, but I confess I am a newbie with mono and monogame. That is why I would like to test.

**Comment by KonajuGames** [comment]
Your original post shows that it is calling "mono" with "MGCB.exe" as part of the parameters.

The executable permissions on ffmpeg and ffprobe were fixed after the 3.4 release.

**Comment by ambs** [comment]
True, the exception shows mono there. But I can't see in the code where it is added.

nevertheless, as I've said before, it is not just the problem of the permissions. After fixing them, command line works, but pipeline tool still fails. And I tried the exact command as presented in the exception. So, something is missing. Still not sure what. And not easy to debug without a compiler :(

**Comment by KonajuGames** [comment]
> True, the exception shows mono there. But I can't see in the code where it is added.

In the code for View.CreateProcess()
https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Gtk/MainWindow.cs#L566

> My app running on Mac says: Failed to get buffer bits: Invalid Value, format=Stereo16, size=0, sampleRate=22050

Is it producing a valid .ogg file in the output?  Using the input file `POL-macaron-island-short.wav`, you should get two files: `POL-macaron-island-short.xnb` and `POL-macaron-island-short.ogg`.

**Comment by dellis1972** [comment]
@ambs 
The appending of mono to the command is handled here



I would highly recommend using the latest development build if the MonoGame.pkg Mac Installer as it will install pretty much everything you need. 

On a side note I would also recommend using the "MonoGame Cross Platform Project" if you are targeting desktop.

**Comment by dellis1972** [comment]
@KonajuGames lol snap ;)

**Comment by dellis1972** [comment]
I have to say the path 

/Volumes/HDD/Applications/....

is a bit weird. Its not the normal path for a Mac. which is usually  

/Applications/..

**Comment by ambs** [comment]
@dellis1972, when you have a 128GB SSD you need to get solutions to store more things. I have a HDD in the CD slot :-)

**Comment by ambs** [comment]
> Is it producing a valid .ogg file in the output? Using the input file POL-macaron-island-short.wav, you should get two files: POL-macaron-island-short.xnb and POL-macaron-island-short.ogg.

It is creating a .m4a file (from the command line). The Pipeline not working.

> I would highly recommend using the latest development build if the MonoGame.pkg Mac Installer as it will install pretty much everything you need. 

Will try and report any news :-)

**Comment by ambs** [comment]
> On a side note I would also recommend using the "MonoGame Cross Platform Project" if you are targeting desktop.

Need to look at that, thanks. If it allows a project to be developed by two guys, one in Mac and another in Windows, it should be really useful.

**Comment by dellis1972** [comment]
Are you able to try to install/move the Pipeline tool on to your main HDD?
Just want to eliminate that as an issue.

**Comment by ambs** [comment]
@dellis1972, in fact I had it there at first. So I do not think that was an issue.

Just let me install the devel version.

**Comment by ambs** [comment]
Pipeline 3.5.x works perfectly.
But I still get a m4a file, that doesn't produce any sound:
 Failed to get buffer bits: Invalid Value, format=Stereo16, size=0, sampleRate=22050

Thanks

**Comment by ambs** [comment]
(I can open a different issue if you wish)

**Comment by KonajuGames** [comment]
> But I still get a m4a file, that doesn't produce any sound:
> Failed to get buffer bits: Invalid Value, format=Stereo16, size=0, sampleRate=22050

Set the target platform to `DesktopGL` in the Pipeline tool (select the root node in the list and set the platform in the Properties window).  This will tell the pipeline to generate a .ogg file, which is what the OS X version of MonoGame expects.  It should have thrown an error long before it got to point where it complained about the buffer bits because it wasn't able to find the .ogg file it was expecting.

There are some usability issues we need to fix up here in regards to selecting the target platform.

**Comment by ambs** [comment]
So, when selecting macOSX in the pipeline shouldn't it use ogg?

In any case, I got this:

```````
ffmpeg version 2.2.3-tessus Copyright (c) 2000-2014 the FFmpeg developers
  built on Jun  4 2014 21:31:51 with clang version 3.3 (tags/RELEASE_33/final)
  configuration: --cc=/opt/local/bin/clang-mp-3.3 --prefix=/Users/tessus/data/ext/ffmpeg/sw --as=yasm --extra-version=tessus --disable-shared --enable-static --disable-ffplay --enable-gpl --enable-pthreads --enable-postproc --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxvid --enable-libspeex --enable-bzlib --enable-zlib --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libxavs --enable-version3 --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvpx --enable-libgsm --enable-libopus --enable-libmodplug --enable-fontconfig --enable-libfreetype --enable-libass --enable-libbluray --enable-filters --disable-indev=qtkit --enable-runtime-cpudetect
  libavutil      52. 66.100 / 52. 66.100
  libavcodec     55. 52.102 / 55. 52.102
  libavformat    55. 33.100 / 55. 33.100
  libavdevice    55. 10.100 / 55. 10.100
  libavfilter     4.  2.100 /  4.  2.100
  libswscale      2.  5.102 /  2.  5.102
  libswresample   0. 18.100 /  0. 18.100
  libpostproc    52.  3.100 / 52.  3.100
Input #0, mp3, from '/var/folders/3h/8h7stdp57hx4fms5l_g5g9n80000gn/T/tmp7d81fcf8.tmp':
  Duration: 00:00:14.84, start: 0.050113, bitrate: 64 kb/s
    Stream #0:0: Audio: mp3, 22050 Hz, stereo, s16p, 64 kb/s
[libvorbis @ 0x103000600] encoder setup failed
Output #0, ogg, to '/var/folders/3h/8h7stdp57hx4fms5l_g5g9n80000gn/T/tmp4060d224.tmp':
    Stream #0:0: Audio: vorbis, 22050 Hz, stereo, fltp, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 -> libvorbis)
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```````

**Comment by ambs** [comment]
tried to convert from wav, same kind of error.

**Comment by ambs** [comment]
Not sure what options are supplied to ffmpeg, but rruning ffmpeg directly (the one bundled with pipeline) with

````
ffmpeg -i file.mp3 file.ogg
`````

creates a ogg file, but it is not recognized by monogame, later.

**Comment by ambs** [comment]
I think the problem was related with the mp3 file I was using.
So, for now, closing this ticket. Will reopen when I notice it failing again.
