### ISSUE TITLE
[Pipeline Tool] Filter Output bug with spritefonts

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#4620]
I was missing the font in my system, and filter output wasn't giving a useful part of the error.

The log:
```
/home/harry/Content/Fonts/Interface.spritefont
	Building Font /home/harry/Content/Fonts/Monospace
	System.Exception: Could not load /home/harry/Content/Fonts/Monospace
  at Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.Process (Microsoft.Xna.Framework.Content.Pipeline.Graphics.FontDescription input, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context) <0x40dc0710 + 0x0042f> in <filename unknown>:0 
/home/harry/Content/Fonts/Interface.spritefont: error: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```

Filter output:
```
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
```

CC. @nkast

**Comment by Tzenchor** [comment]
I think I fixed that as part of #4537.
If you want the fix now, or want to try it, it is the catch clause in `FontDescriptionImporter.Process`, simply comment the log message and rethrow the exception, or remove the try/catch completely.

The log you see is because that catch is hiding any exception thrown in it, and an empty SpriteFontContent is being passed to the next step in the pipeline

**Comment by cra0zy** [comment]
Good to hear.

**Comment by emhean** [comment]
shit

**Comment by selimanac** [comment]
Still not working on mac

`Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index`

**Comment by cra0zy** [comment]
It was never fixed... so you are stating the obvious...

**Comment by louisgv** [comment]
This is still an issue on the MacOSX Pipeline tool. All other platform (Linux and Windows) works great. 

Version: MonoGame Pipeline Tool 3.5.1.1679

I'm up to fix this, just need someone to pin-point where I should look.

Error:
![image](https://cloud.githubusercontent.com/assets/6723574/20206678/28c762b8-a7b0-11e6-86b5-b91ece4c0db4.png)

**Comment by emhean** [comment]
Why did I get this mail? :o

**Comment by iliakonnov** [comment]
Not working on Ubuntu 16.04.
Mono version 4.6.2
MonoDevelop 6.1.2
MonoGame Pipeline Tool 3.5.1.1679.
![06-02-2017_16 59 39 649115980](https://cloud.githubusercontent.com/assets/9402179/22649935/2af3f010-ec8e-11e6-9fc0-7e2862b8c27c.png)

`Building Font /home/user/cSharp/snake_game/snake_game/Content/images/Arial
	System.Exception: Could not load /home/user/cSharp/snake_game/snake_game/Content/images/Arial
  at Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.Process (Microsoft.Xna.Framework.Content.Pipeline.Graphics.FontDescription input, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context) [0x00166] in <279c948b8d624a51ba8f1bf6590afc0d>:0 
/home/user/cSharp/snake_game/snake_game/Content/images/Arial.spritefont: error: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index`

**Comment by cra0zy** [comment]
To quote myself:

> It was never fixed... so you are stating the obvious...

**Comment by iliakonnov** [comment]
I just wanted to say that it doesn't work on Linux too

**Comment by cra0zy** [comment]
My original post was about all 3 systems.

**Comment by emhean** [comment]
Fix this

**Comment by Rennan24** [comment]
DELET THIS

**Comment by Rennan24** [comment]
Wow you actually deleted it 😮  Also it would be nice if this was actually fixed, especially considering this issue was opened last year, and none of the fonts can build with this bug.

**Comment by Jjagg** [comment]
> none of the fonts can build with this bug.

@Rennan24 You must've misread something. This issue is about the error when building a font that is not on your system showing the wrong message. Fonts build fine. If you have a specific problem, I recommend you open a new issue.

**Comment by Rennan24** [comment]
> Fonts build fine.
@Jjagg Oh crap really? Dang, I'll check again to see if I did anything wrong but none of my fonts were building even the default Arial one. Thanks for the heads up though 😅

**Comment by bradlak** [comment]
still not working :(

**Comment by NickWestwood** [comment]
Any update on this? I'm using mac and having a lot of trouble trying to get fonts to work. having the same error as above and a different error when updating to the latest version of the pipeline tool...

**Comment by Jjagg** [comment]
@NickWestwood That is a different error. This discussion is about confusing error messages when a font is missing from the system when **building** a spritefont with the Pipeline Tool. A ContentLoadException is thrown **at runtime** when you try to load a font that is already built. In your case, the font is not in the expected location. 

From the [docs](http://www.monogame.net/documentation/?page=Using_The_Pipeline_Tool):
> Once you have built your content you have a few different ways to add the xnb's to your game project. They all have the same goal, to get the built xnb's in your project output folder so a ContentManager can easily find and load them.

You need to first build the content and then put it in your build folder. MonoGame has a little bit of automagic set up in the templates, which runs tooling when the project is built. The MonoGame content tooling will build your content and copy it to the right location. How it works is explained in the docs page I linked (it's the MonoGameContentReference build action). Maybe that's not set up correctly, but reading through should help you figure it out. Hope that helps :) 

If you need help figuring it out, please open a topic on the [forum](http://community.monogame.net/) instead of discussing it here.
